Switch to packages from 'litex-hub' channel
SymbiFlow/symbiflow-arch-defs pull request #1795
Opened 2020-11-20 09:42 UTC by tjurtsch

Most of the Conda dependencies are now provided via 'litex-hub' channel.

2020-11-20 17:19 UTC, litghost commented on environment.yml
> +  - litex-hub::symbiflow-yosys
Regardless of whether the packages come from symbiflow or litex-hub channel, removing version pinning right now will result in unstable builds.  What is the plan to deal with incompatible packages?  I'm specifically concerned with VTR and yosys packages, as those are the ones mostly likely to break.

2020-11-20 23:50 UTC, mithro commented
@PiotrZierhoffer - I think we need the version pinning process here (and auto rolling bot).

2020-11-24 12:01 UTC, ajelinski commented
@litghost @mithro All `litex-conda-*`-based packages have been pinned to their latest versions available in the `litex-hub` channel. Being the latest ones most of those versions must've been tested in the previous CI of this PR so I hope this would be successful too.

`symbiflow` channel has been removed because currently all packages `defaults` channel lacks are taken from the `litex-hub` channel. I also rebased commits on top of the current master.

2020-11-25 13:43 UTC, ajelinski commented
@litghost are you able to restart `Documentation` and `Architecture Definitions` tests alone? AD failed only because the `Documentation` failed which had some error which seems to be some random Conda or connection issue:
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

2020-11-26 14:01 UTC, ajelinski commented
The branch was rebased again because there was a conflict on `symbiflow-vtr` version which needed to be resolved.

The `symbiflow-vtr` basically stays the same after the change because it was built using the latest `d6d69ff` commit. It will be just taken from the `litex-hub` channel.

2020-11-30 17:52 UTC, litghost requested changes
With the move to `litex-hub`, how are changes to packages introduced?  What is the new process?  For example, what does https://github.com/SymbiFlow/conda-packages/pull/143 look like?

Also the `litex-hub` packages are only built with `python 3.7`, and the packages from `SymbiFlow/conda-packages` are only built with `python 3.8`.  Should the `litex-hub` packages be built with `python 3.7` and `python 3.8`?  Should `litex-hub` simply move from `python 3.7` to `python 3.8`?

Until these questions are answered, this PR cannot be merged.  If these questions have already been asked and answered, where are the answers?  Thanks.

2020-11-30 21:06 UTC, litghost commented
So as a concrete question, how does the labelling on litex-hub work?  When do packages get the `main` label?

2020-11-30 23:43 UTC, PiotrZierhoffer commented
@litghost I added a description of the transition we want to have: https://github.com/SymbiFlow/conda-packages/issues/154

The process of merging in SymbiFlow/conda-packages#143 will look, I assume, quite similar. 

I'll verify the Python thingy. Is conda-packages actually relying on 3.8?

Labels are attached to packages when they are built as part of a PR. When they get merged and the CI is green, they are moved to main.

2020-12-04 18:20 UTC, litghost commented
Thanks @piotr-binkowski and @ajelinski, I've take this PR and iterated on it in #1816

2020-12-08 17:45 UTC, litghost commented
Superceed #1816

2020-12-08 17:45 UTC, closed without merging

2020-12-08 19:31 UTC, ajelinski commented
Thanks @litghost, it's great to have it merged.