Define DBROOT after DEVICE is set
SymbiFlow/symbiflow-arch-defs pull request #1986
Opened 2021-01-28 18:45 UTC by nickoe

DBROOT depends on the DEVICE variable, so we need to be past any code
that set DEVICE before settting DBROOT.

This cause nmigen fail when using the symbiflow toolchain. See:
https://github.com/SymbiFlow/symbiflow-examples/issues/123

This regression was caused in b35514859f7f02c289c2f6bc058fd3ca1c00143b

Signed-off-by: Nick Østergaard <oe.nick@gmail.com>

2021-01-28 18:58 UTC, acomodi requested changes
Thanks for the fix!

Some minor comments but otherwise LGTM

2021-01-28 19:02 UTC, nickoe commented on tests/9-soc/picosoc/firmware/Makefile
> +OD = riscv32-unknown-elf-objdump
Yeah, that commit should not have been included, I will force push in a moment.

2021-01-28 19:15 UTC, nickoe commented
@acomodi Please review again :)

2021-01-29 19:19 UTC, nickoe commented
I rebased the patch.

2021-01-31 10:13 UTC, nickoe commented
@acomodi and @litghost What to do about the "Architecture Definitions (Presubmit)" failure?

2021-01-31 16:17 UTC, merged