xc7: techmap: Remove localparam from generate blocks
SymbiFlow/symbiflow-arch-defs pull request #2039
Opened 2021-02-18 17:56 UTC by dnltz

Yosys throws following error:
	Parameter x with non-constant value!

This only happens on localparams which are included in a generate if block.
Move the localparam statement out of the generate fixes the issue.

Closes #2020 

Does not feel right to add nested "? :" statement but do not know a better solution for else if blocks.

2021-02-18 17:58 UTC, litghost commented
This looks reasonable, did you test with the latest Yosys and see if it accepts the Verilog?  The CI should verify that the flow doesn't break.

2021-02-18 18:01 UTC, dnltz commented
Yes, I used the " linux-64/yosys-v0.9_5191_geff18a2b-20210209_143455_py37.tar.bz2" version which is 9 days old. I run into the same issue from #2020 and with these changes it works again.

2021-02-21 18:28 UTC, dnltz commented
@litghost - The CI output looks a little bit strange. Can we restart it?

2021-02-22 09:36 UTC, acomodi requested changes
Comment in

2021-02-22 09:36 UTC, acomodi commented on xc/xc7/techmap/cells_map.v
> +  localparam EFF_WRITE_WIDTH_B = (RAM_MODE == "SDP" && WRITE_WIDTH_B == 36) ? 18 : WRITE_WIDTH_B;
Hi @dnltz, These lines are not equivalent to the original version, causing CI error.

Should be like:
```
localparam EFF_READ_WIDTH_A = (RAM_MODE == "SDP" && READ_WIDTH_A > 36) ? 36 : READ_WIDTH_A;
```

For reference, the CI error is related to BRAM_READ_WIDTH:
```
Traceback (most recent call last):
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/third_party/symbiflow-xc-fasm2bels/fasm2bels/__main__.py", line 4, in <module>
    main()
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/third_party/symbiflow-xc-fasm2bels/fasm2bels/fasm2bels.py", line 443, in main
    process_tile(top, tile, tile_features)
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/third_party/symbiflow-xc-fasm2bels/fasm2bels/fasm2bels.py", line 107, in process_tile
    PROCESS_TILE[tile_type](top.conn, top, tile, tile_features)
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/third_party/symbiflow-xc-fasm2bels/fasm2bels/models/bram_models.py", line 1382, in process_bram
    sites.append(process_bram_site(top, brams[bram], bram_features[bram]))
  File "/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/third_party/symbiflow-xc-fasm2bels/fasm2bels/models/bram_models.py", line 518, in process_bram_site
    assert 'READ_WIDTH_B_18' in set_features
```

2021-02-22 17:22 UTC, dnltz commented on xc/xc7/techmap/cells_map.v
> +  localparam EFF_WRITE_WIDTH_B = (RAM_MODE == "SDP" && WRITE_WIDTH_B == 36) ? 18 : WRITE_WIDTH_B;
Ah! Thanks for pointing me out the issue.

2021-02-24 09:01 UTC, acomodi approved these changes
LGTM. I believe it might be worth to also update yosys to the latest version and check this indeed solves the original problem of the `localparam` within  a generate/if statement. @litghost thoughts on that?

2021-02-24 16:04 UTC, litghost commented
> LGTM. I believe it might be worth to also update yosys to the latest version and check this indeed solves the original problem of the `localparam` within a generate/if statement. @litghost thoughts on that?

I asked @dnltz if they tested against the new yosys, and they said they had.

2021-02-24 16:05 UTC, merged