quicklogic: pp3: added primitives
SymbiFlow/symbiflow-arch-defs pull request #2170
Opened 2021-06-22 14:06 UTC by acomodi

This PR adds all the primitives XMLs required for the PP3 devices.

2021-06-24 08:14 UTC, mkurc-ant requested changes
A few files require attention but otherwise LGTM

2021-06-24 08:14 UTC, mkurc-ant commented on quicklogic/pp3/primitives/fpga_interconnect/fpga_interconnect.sim.v
> +module fpga_interconnect(
This one actually does not belong to the architecture. This is a cell present in post-pnr verilog netlist from VPR. I'm not sure whether we want it here or eg. in `yosys/techmap/cells_sim.v`. I guess the only reason why it ended up here is to be included in the auto-generated `cells_sim.v` for the arch.

2021-06-24 08:14 UTC, mkurc-ant commented on quicklogic/pp3/primitives/ramfifo/ram.sim.v
> +`timescale 10 ps /1 ps
This file could use indentation fixing and/or reformatting with Verible

2021-06-24 08:14 UTC, mkurc-ant commented on quicklogic/pp3/primitives/ramfifo/ramfifo.sim.v
> +`timescale 1 ns /10 ps
This one could make use of reformatting too. It may be worth to compare models included here with those in `symbiflow-yosys-plugins`. I think that they may be the same and if so then there is no reason to have them here.

2021-06-24 08:18 UTC, acomodi commented on quicklogic/pp3/primitives/fpga_interconnect/fpga_interconnect.sim.v
> +module fpga_interconnect(
Yeah, the `cells_sim.v` file is generated by grouping and merging the various `sim.v` files from the various primitives. There is actually no static cells_sim in the techmap, so I think to conform to the way the `cells_sim.v` is generated, this might just stay here.

2021-06-24 08:22 UTC, mkurc-ant commented on quicklogic/pp3/primitives/fpga_interconnect/fpga_interconnect.sim.v
> +module fpga_interconnect(
Ok. If you can then maybe add a comment that this is only a cell emitted by VPR and not a part of the PP3 arch.

2021-06-24 08:45 UTC, acomodi commented on quicklogic/pp3/primitives/ramfifo/ramfifo.sim.v
> +`timescale 1 ns /10 ps
Yeah, I have checked and the three sim files added in ramfifo are merged all together in the `pp3_brams_sim.v` file in the yosys-plugins. I have removed ramfifo.

2021-06-24 08:46 UTC, acomodi commented on quicklogic/pp3/primitives/fpga_interconnect/fpga_interconnect.sim.v
> +module fpga_interconnect(
Done

2021-07-06 15:28 UTC, lpawelcz commented
This PR should me merged after https://github.com/SymbiFlow/symbiflow-arch-defs/pull/2167

2021-07-07 08:58 UTC, acomodi commented
This PR only adds primitives to the quicklogic subdirectory and does not modify at all any common infrastructure that may affect xc7, merging.

2021-07-07 08:58 UTC, merged